'use client';
import { useEffect, useState } from 'react';
import { approvePlace, getCurrentAdminRole, listAuditLogs, listUserRoles, rejectPlace, upsertUserRole } from '@/services/adminService';
import { deletePlace, listApprovedPlaces, listStagingPlaces, saveStagingPlace, type PlaceRecord } from '@/services/placesService';
import { importPlaces } from '@/services/importService';

export default function AdminTab({ onEdit }: { onEdit: (place: PlaceRecord) => void }) {
  const [role, setRole] = useState<string | null>('checking'); const [staging, setStaging] = useState<PlaceRecord[]>([]); const [approved, setApproved] = useState<PlaceRecord[]>([]); const [logs, setLogs] = useState<any[]>([]); const [roles, setRoles] = useState<any[]>([]); const [message, setMessage] = useState(''); const [importText, setImportText] = useState(''); const [userId, setUserId] = useState(''); const [newRole, setNewRole] = useState<'admin'|'editor'|'viewer'>('viewer'); const [aiProvider, setAiProvider] = useState('jarvis-gpt4o');
  const load = async () => { try { setRole(await getCurrentAdminRole()); setStaging(await listStagingPlaces()); setApproved(await listApprovedPlaces()); setLogs(await listAuditLogs()); setRoles(await listUserRoles()); } catch (e) { setMessage(e instanceof Error ? e.message : 'Admin load failed'); } };
  const statusCounts = staging.reduce((acc, place) => { const status = place.status || 'pending'; acc[status] = (acc[status] || 0) + 1; return acc; }, {} as Record<string, number>);
  useEffect(() => { load(); }, []);
  const guarded = async (fn: () => Promise<void>) => { try { await fn(); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Action failed'); } };
  if (!role || role === 'checking') return <div className="bg-gray-800 p-4 rounded border border-gray-700">Admin role required. Sign in with a user listed in user_roles.</div>;
  return <div className="space-y-6 animate-fade-in">
    {message && <div className="bg-yellow-950 border border-yellow-700 rounded p-2 text-sm">{message}</div>}
    <div className="grid grid-cols-3 gap-2 text-xs"><div className="bg-gray-800 border border-gray-700 rounded p-2">Pending: {statusCounts.pending || 0}</div><div className="bg-gray-800 border border-gray-700 rounded p-2">Approved: {(statusCounts.approved || 0) + approved.length}</div><div className="bg-gray-800 border border-gray-700 rounded p-2">Rejected: {statusCounts.rejected || 0}</div></div>
    <div className="bg-gray-800 p-4 rounded-lg border border-gray-700 flex justify-between items-center"><div><h3 className="font-bold text-white text-sm">🧠 สมองส่วนกลาง (AI Routing)</h3><p className="text-xs text-gray-400">Jarvis/Sentinel/Foresight provider agnostic monitoring readiness</p></div><select className="bg-gray-900 border border-gray-600 rounded p-2 text-xs" value={aiProvider} onChange={(e) => setAiProvider(e.target.value)}><option value="jarvis-gpt4o">Jarvis</option><option value="sentinel-claude">Sentinel</option><option value="foresight-gemini">Foresight</option></select></div>
    <section className="bg-gray-800 p-4 rounded-lg border border-gray-700"><h3 className="font-bold mb-3">Doctor Gatekeeper: รออนุมัติ ({staging.length})</h3><div className="space-y-2">{staging.map((p) => <div key={p.id} className="bg-gray-900 p-2 rounded text-sm flex flex-col md:flex-row md:items-center gap-2 justify-between"><span>{p.name} — {p.province} — {p.status}</span><div className="flex gap-2"><button className="bg-green-700 px-2 py-1 rounded" onClick={() => guarded(async () => { await approvePlace(p); })}>อนุมัติ</button><button className="bg-yellow-700 px-2 py-1 rounded" onClick={() => guarded(async () => { await rejectPlace(p.id!, prompt('เหตุผลการ reject') || 'ไม่ผ่านการตรวจ'); })}>Reject</button><button className="bg-purple-700 px-2 py-1 rounded" onClick={() => onEdit(p)}>แก้ไข</button><button className="bg-red-800 px-2 py-1 rounded" onClick={() => guarded(async () => { await deletePlace(p.id!, 'staging_places'); })}>ลบ</button></div></div>)}</div></section>
    <section className="bg-gray-800 p-4 rounded-lg border border-gray-700"><h3 className="font-bold mb-3">Production Search Data ({approved.length})</h3>{approved.map((p) => <div key={p.id} className="bg-gray-900 p-2 rounded text-sm flex justify-between mb-2"><span>{p.name} — {p.category}</span><div className="flex gap-2"><button className="bg-purple-700 px-2 py-1 rounded" onClick={() => onEdit(p)}>แก้ไข</button><button className="bg-red-800 px-2 py-1 rounded" onClick={() => guarded(async () => { await deletePlace(p.id!, 'production_places'); })}>ลบ</button></div></div>)}<button className="mt-2 bg-blue-700 px-3 py-2 rounded text-sm" onClick={() => guarded(async () => { await saveStagingPlace({ name: 'New place', province: 'กรุงเทพมหานคร', category: 'อื่นๆ (โปรดระบุ)', rating: 5, amenities: [], alerts: [], status: 'pending' }); })}>เพิ่มข้อมูลตัวอย่างเพื่อแก้ไข</button></section>
    <section className="bg-gray-800 p-4 rounded-lg border border-gray-700"><h3 className="font-bold mb-2">Import CSV/JSON</h3><textarea className="w-full h-28 bg-gray-900 border border-gray-600 rounded p-2 text-xs" value={importText} onChange={(e) => setImportText(e.target.value)} placeholder="name,province,category,rating" /><button className="mt-2 bg-blue-700 px-3 py-2 rounded" onClick={() => guarded(async () => { const result = await importPlaces(importText); setMessage(`Imported ${result.imported}/${result.total}`); })}>Import</button></section>
    <section className="bg-gray-800 p-4 rounded-lg border border-gray-700"><h3 className="font-bold mb-2">Admin users / roles</h3><div className="flex gap-2 mb-3"><input className="flex-1 bg-gray-900 border border-gray-600 rounded p-2" placeholder="user uuid" value={userId} onChange={(e) => setUserId(e.target.value)} /><select className="bg-gray-900 border border-gray-600 rounded p-2" value={newRole} onChange={(e) => setNewRole(e.target.value as any)}><option>viewer</option><option>editor</option><option>admin</option></select><button className="bg-blue-700 px-3 rounded" onClick={() => guarded(async () => { await upsertUserRole(userId, newRole); })}>Save</button></div>{roles.map((r) => <div className="text-xs text-gray-300" key={r.user_id}>{r.user_id}: {r.role}</div>)}</section>
    <section className="bg-gray-800 p-4 rounded-lg border border-gray-700"><h3 className="font-bold mb-2">Audit logs</h3>{logs.map((l) => <div className="text-xs text-gray-300" key={l.id}>{l.created_at} — {l.action} — {l.entity_type}</div>)}</section>
  </div>;
}
