'use client';
import { useEffect, useMemo, useState } from 'react';
import { ALERTS, AMENITIES, CATEGORIES, PROVINCES, SUBCATEGORIES } from '@/lib/constants';
import { listApprovedPlaces, type PlaceRecord } from '@/services/placesService';
import { listPlaceMedia, type PlaceMedia } from '@/services/mediaService';

export default function SearchTab({ refreshKey, onEdit }: { refreshKey: number; onEdit: (place: PlaceRecord) => void }) {
  const [places, setPlaces] = useState<PlaceRecord[]>([]); const [media, setMedia] = useState<Record<string, PlaceMedia[]>>({}); const [error, setError] = useState('');
  const [filters, setFilters] = useState({ keyword: '', province: '', category: '', sub_category: '', amenity: '', alert: '', rating: 0 });
  useEffect(() => { listApprovedPlaces({ keyword: filters.keyword, province: filters.province, category: filters.category, sub_category: filters.sub_category, amenities: filters.amenity ? [filters.amenity] : [], alerts: filters.alert ? [filters.alert] : [], rating: filters.rating || undefined }).then(async (rows) => { setPlaces(rows); setError(''); const pairs = await Promise.all(rows.filter((p) => p.id).map(async (p) => [p.id!, await listPlaceMedia(p.id!)] as const).slice(0, 20)); setMedia(Object.fromEntries(pairs)); }).catch((e) => setError(e.message)); }, [filters, refreshKey]);
  const suggestions = useMemo(() => [...new Set(places.flatMap((p) => [p.name, p.province, p.category, p.sub_category].filter(Boolean) as string[]))], [places]);
  const share = async (p: PlaceRecord) => { const text = `${p.name} (${p.province}) ${p.google_maps_url || ''}`; await navigator.clipboard?.writeText(text); alert('คัดลอกข้อมูลสำหรับแชร์แล้ว'); };
  return <div className="space-y-6 animate-fade-in">
    <div className="bg-gray-800 p-4 rounded-lg shadow-md border border-gray-700 space-y-3">
      <input list="search-suggestions" placeholder="🔍 ค้นหาสถานที่, หมวดหมู่, จุดเด่น..." className="w-full p-3 bg-gray-900 rounded border border-gray-600" value={filters.keyword} onChange={(e) => setFilters({...filters, keyword: e.target.value})} /><datalist id="search-suggestions">{suggestions.map((s) => <option key={s} value={s} />)}</datalist>
      <div className="grid md:grid-cols-3 gap-2 text-sm"><select className="p-2 bg-gray-900 rounded border border-gray-600" value={filters.province} onChange={(e) => setFilters({...filters, province: e.target.value})}><option value="">ทุกจังหวัด</option>{PROVINCES.map((p) => <option key={p}>{p}</option>)}</select><select className="p-2 bg-gray-900 rounded border border-gray-600" value={filters.category} onChange={(e) => setFilters({...filters, category: e.target.value})}><option value="">ทุกหมวดหมู่</option>{CATEGORIES.map((c) => <option key={c}>{c}</option>)}</select><select className="p-2 bg-gray-900 rounded border border-gray-600" value={filters.sub_category} onChange={(e) => setFilters({...filters, sub_category: e.target.value})}><option value="">ทุกหมวดย่อย</option>{SUBCATEGORIES.map((s) => <option key={s}>{s}</option>)}</select><select className="p-2 bg-gray-900 rounded border border-gray-600" value={filters.amenity} onChange={(e) => setFilters({...filters, amenity: e.target.value})}><option value="">ทุกสิ่งอำนวยความสะดวก</option>{AMENITIES.map((a) => <option key={a}>{a}</option>)}</select><select className="p-2 bg-gray-900 rounded border border-gray-600" value={filters.alert} onChange={(e) => setFilters({...filters, alert: e.target.value})}><option value="">ทุกข้อควรระวัง</option>{ALERTS.map((a) => <option key={a}>{a}</option>)}</select><select className="p-2 bg-gray-900 rounded border border-gray-600" value={filters.rating} onChange={(e) => setFilters({...filters, rating: Number(e.target.value)})}><option value="0">ทุกดาว</option>{[5,4,3,2,1].map((r) => <option key={r} value={r}>{r}+ ดาว</option>)}</select></div>
    </div>
    {error && <div className="bg-red-950 border border-red-700 rounded p-3 text-sm">Search runtime blocked: {error}</div>}
    <h3 className="text-sm font-bold text-gray-300">ผลการค้นหา {places.length} รายการ</h3>
    <div className="grid md:grid-cols-2 gap-3">{places.map((p) => <article key={p.id} className="bg-gray-800 rounded-lg overflow-hidden border border-gray-700">
      <div className="h-36 bg-gray-700 flex items-center justify-center text-gray-400 text-xs">{media[p.id || '']?.[0]?.public_url ? <img src={media[p.id || ''][0].public_url!} alt="" className="h-full w-full object-cover" /> : '[รูปภาพ/VDO สถานที่]'}</div>
      <div className="p-3 space-y-2"><h4 className="font-bold text-blue-400">{p.name}</h4><p className="text-xs text-gray-400">⭐ {p.rating} | {p.category}{p.sub_category ? ` / ${p.sub_category}` : ''} | {p.province}</p><p className="text-sm whitespace-pre-line">{p.suggestion || 'ไม่มีคำแนะนำเพิ่มเติม'}</p><p className="text-xs text-gray-400">โทร/ไลน์: {p.phone || '-'} | ผู้แนะนำ: {p.recommender || '-'}</p><div className="flex gap-1 flex-wrap text-[10px]">{p.amenities?.map((a) => <span key={a} className="bg-green-900 text-green-300 px-1.5 py-0.5 rounded">{a}</span>)}{p.alerts?.map((a) => <span key={a} className="bg-yellow-900 text-yellow-200 px-1.5 py-0.5 rounded">{a}</span>)}</div><div className="flex gap-2 flex-wrap text-xs"><a className="bg-blue-700 px-2 py-1 rounded" href={p.google_maps_url || `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.name + ' ' + p.province)}`} target="_blank">นำทาง</a><button className="bg-gray-700 px-2 py-1 rounded" onClick={() => share(p)}>แชร์</button><button className="bg-purple-700 px-2 py-1 rounded" onClick={() => onEdit(p)}>แก้ไข</button></div></div>
    </article>)}</div>
  </div>;
}
